### ISSUE TITLE
northbound and southbound counts are different 

### ISSUE THREAD

**Issue by JanetMatsen** [UWSEDS/uwseds.github.io#1]
The “fremont_bridge_nb” and “fremont_bridge_sb” values are not identical.  While head() makes it seem like they would be, tail() shows values where this is not true. 

my code:
d = pd.read_csv('../data/4xy5-26gy.csv')
d.tail()

**Comment by jakevdp** [comment]
Thanks – @joseph-hellerstein fixed this on the website.

**Comment by joseph-hellerstein** [comment]
Thanks

**Comment by joseph-hellerstein** [comment]
See Valentine's pull request so that you can follow her lecture on SQL.

**Comment by bernease** [comment]
Closed for time.
